# Generated by Django 5.2.8 on 2026-01-20 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="답변 내용")),
                ("is_adopted", models.BooleanField(default=False, verbose_name="채택 여부")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 답변",
                "verbose_name_plural": "질문 답변 목록",
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="AnswerComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="댓글 내용")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="qna.answer",
                        verbose_name="답변",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 답변 댓글",
                "verbose_name_plural": "질문 답변 댓글 목록",
                "db_table": "answer_comments",
            },
        ),
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.CharField(max_length=255, verbose_name="이미지 URL")),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="qna.answer",
                        verbose_name="답변",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 답변 이미지",
                "verbose_name_plural": "질문 답변 이미지 목록",
                "db_table": "answer_image",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="조회수")),
                ("is_ai_answered", models.BooleanField(default=False, verbose_name="AI 답변 여부")),
                ("is_staff_answered", models.BooleanField(default=False, verbose_name="운영진 답변 여부")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문",
                "verbose_name_plural": "질문 목록",
                "db_table": "question",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="qna.question",
                verbose_name="질문",
            ),
        ),
        migrations.CreateModel(
            name="QuestionAIAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output", models.TextField(verbose_name="AI 답변 본문")),
                (
                    "using_model",
                    models.CharField(
                        choices=[("Gemini", "Gemini"), ("GPT", "GPT")],
                        default="Gemini",
                        max_length=20,
                        verbose_name="사용된 AI 모델",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_answer",
                        to="qna.question",
                        verbose_name="질문",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 AI 답변",
                "verbose_name_plural": "질문 AI 답변 목록",
                "db_table": "question_ai_answer",
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=15, verbose_name="카테고리명")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="qna.questioncategory",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 카테고리",
                "verbose_name_plural": "질문 카테고리 목록",
                "db_table": "question_category",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="qna.questioncategory",
                verbose_name="카테고리",
            ),
        ),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.CharField(max_length=255, verbose_name="이미지 URL")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="qna.question",
                        verbose_name="질문",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 이미지",
                "verbose_name_plural": "질문 이미지 목록",
                "db_table": "question_image",
            },
        ),
    ]
