# Generated by Django 5.2.8 on 2026-01-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="강좌명")),
                ("tag", models.CharField(max_length=3, verbose_name="태그")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="설명")),
                (
                    "thumbnail_img_url",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="썸네일 URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "강좌",
                "verbose_name_plural": "강좌 목록",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(verbose_name="기수")),
                ("max_student", models.PositiveSmallIntegerField(verbose_name="최대 학생 수")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[("PREPARING", "모집중"), ("IN_PROGRESS", "진행중"), ("FINISHED", "종료")],
                        default="PREPARING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="courses.course",
                        verbose_name="강좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "기수",
                "verbose_name_plural": "기수 목록",
                "db_table": "course_cohorts",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30, verbose_name="주제 타이틀")),
                ("number_of_days", models.PositiveSmallIntegerField(verbose_name="일수")),
                ("number_of_hours", models.PositiveSmallIntegerField(verbose_name="시간")),
                (
                    "thumbnail_img_url",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="썸네일 URL"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="상태")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.course",
                        verbose_name="강좌",
                    ),
                ),
            ],
            options={
                "verbose_name": "과목",
                "verbose_name_plural": "과목 목록",
                "db_table": "course_subjects",
            },
        ),
    ]
