# Generated by Django 5.2.8 on 2026-01-22 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CohortStudent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        db_column="cohort_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_students",
                        to="courses.cohort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "코호트 수강생",
                "verbose_name_plural": "코호트 수강생들",
                "db_table": "cohort_students",
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="cohort_stud_user_id_2af506_idx"),
                    models.Index(fields=["cohort"], name="cohort_stud_cohort__c8757b_idx"),
                ],
            },
        ),
    ]
