# Generated by Django 5.2.8 on 2026-01-21 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qna", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=30, verbose_name="세션 제목")),
                (
                    "using_model",
                    models.CharField(
                        choices=[("Gemini", "Gemini"), ("GPT", "GPT")],
                        default="Gemini",
                        max_length=20,
                        verbose_name="사용 모델",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("IDLE", "질문 대기 중"), ("RESPONDING", "답변 생성 중")],
                        default="IDLE",
                        help_text="AI가 답변 중일 때는 추가 질문을 막기 위한 상태 필드",
                        max_length=20,
                        verbose_name="세션 상태",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="사용자가 'x'를 누르거나 새로고침하여 세션이 종료되면 False로 변경됩니다.",
                        verbose_name="활성화 여부",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to="qna.question",
                        verbose_name="질문 ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 세션",
                "verbose_name_plural": "챗봇 세션 목록",
                "db_table": "chatbot_session",
            },
        ),
        migrations.CreateModel(
            name="ChatbotMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "사용자"), ("AICB", "AI챗봇")],
                        default="USER",
                        max_length=10,
                        verbose_name="발화주체",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_messages",
                        to="chatbot.chatbotsession",
                        verbose_name="세션 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 메세지",
                "verbose_name_plural": "챗봇 메시지 목룍",
                "db_table": "chatbot_message",
            },
        ),
    ]
