# Generated by Django 5.2.8 on 2026-01-21 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qna", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=30, verbose_name="세션 제목")),
                (
                    "using_model",
                    models.CharField(
                        choices=[("Gemini", "Gemini"), ("GPT", "GPT")],
                        default="Gemini",
                        max_length=20,
                        verbose_name="사용 모델",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to="qna.question",
                        verbose_name="질문 ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 세션",
                "verbose_name_plural": "챗봇 세션 목록",
                "db_table": "chatbot_session",
            },
        ),
        migrations.CreateModel(
            name="ChatbotCompletions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "role",
                    models.CharField(
                        choices=[("User", "사용자"), ("Assistant", "AI챗봇")],
                        default="User",
                        max_length=10,
                        verbose_name="발화주체",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_completions",
                        to="chatbot.chatbotsession",
                        verbose_name="세션 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "챗봇 메세지",
                "verbose_name_plural": "챗봇 메시지 목룍",
                "db_table": "chatbot_completion",
            },
        ),
        migrations.AddConstraint(
            model_name="chatbotsession",
            constraint=models.UniqueConstraint(fields=("user", "question"), name="unique_user_question_session"),
        ),
    ]
