# Generated by Django 5.2.8 on 2026-01-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotcompletions",
            options={"verbose_name": "챗봇 메세지", "verbose_name_plural": "챗봇 메시지 목록"},
        ),
    ]
