# Generated by Django 5.2.8 on 2026-02-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatbotcompletions_options"),
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsession",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatbot_sessions",
                to="qna.question",
                verbose_name="질문 ID",
            ),
        ),
    ]
