from __future__ import annotations

from typing import NoReturn

from rest_framework import status

from apps.exams.constants import ErrorMessages
from apps.exams.exceptions import ErrorDetailException

ERROR_STATUS_MAP: dict[ErrorMessages, int] = {
    # 400
    ErrorMessages.INVALID_CHECK_CODE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_EXAM_SESSION: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_EXAM_CREATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_EXAM_LIST_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_EXAM_UPDATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_EXAM_DELETE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_QUESTION_CREATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_QUESTION_UPDATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_QUESTION_DELETE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_CREATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_LIST_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_DETAIL_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_UPDATE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_STATUS_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_DEPLOYMENT_DELETE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_SUBMISSION_LIST_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_SUBMISSION_DETAIL_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_SUBMISSION_DELETE_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_SHORT_ANSWER_TYPE: status.HTTP_400_BAD_REQUEST,
    ErrorMessages.INVALID_SHORT_ANSWER_LENGTH: status.HTTP_400_BAD_REQUEST,
    # 401
    ErrorMessages.UNAUTHORIZED: status.HTTP_401_UNAUTHORIZED,
    # 403
    ErrorMessages.FORBIDDEN: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_STAFF_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_LIST_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_CREATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_UPDATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_DELETE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_QUESTION_CREATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_QUESTION_UPDATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_QUESTION_DELETE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_CREATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_DETAIL_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_LIST_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_UPDATE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_STATUS_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_DEPLOYMENT_DELETE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_SUBMISSION_LIST_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_SUBMISSION_DETAIL_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_SUBMISSION_DELETE_PERMISSION: status.HTTP_403_FORBIDDEN,
    ErrorMessages.NO_EXAM_TAKE_PERMISSION: status.HTTP_403_FORBIDDEN,
    # 404
    ErrorMessages.EXAM_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.EXAM_ADMIN_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.EXAM_UPDATE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.EXAM_DELETE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.SUBJECT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.QUESTION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.QUESTION_UPDATE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.DEPLOYMENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.DEPLOYMENT_TARGET_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.DEPLOYMENT_UPDATE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.DEPLOYMENT_DELETE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.SUBMISSION_LIST_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.SUBMISSION_DETAIL_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.SUBMISSION_DELETE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorMessages.USER_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    # 409
    ErrorMessages.EXAM_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.EXAM_UPDATE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.EXAM_DELETE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.QUESTION_CREATE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.QUESTION_UPDATE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.QUESTION_DELETE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.DUPLICATE_DEPLOYMENT: status.HTTP_409_CONFLICT,
    ErrorMessages.DEPLOYMENT_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.DEPLOYMENT_DELETE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorMessages.SUBMISSION_ALREADY_SUBMITTED: status.HTTP_409_CONFLICT,
    ErrorMessages.SUBMISSION_DELETE_CONFLICT: status.HTTP_409_CONFLICT,
    # 410
    ErrorMessages.EXAM_CLOSED: status.HTTP_410_GONE,
    ErrorMessages.EXAM_ALREADY_CLOSED: status.HTTP_410_GONE,
    # 423
    ErrorMessages.EXAM_NOT_AVAILABLE: status.HTTP_423_LOCKED,
}


def raise_error(message: ErrorMessages, status_override: int | None = None) -> NoReturn:
    status_code = status_override or ERROR_STATUS_MAP.get(message)
    if status_code is None:
        status_code = status.HTTP_400_BAD_REQUEST
    raise ErrorDetailException(message.value, status_code)
