# Generated by Django 5.2.8 on 2026-01-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="시험 제목")),
                ("thumbnail_img_url", models.CharField(max_length=255, verbose_name="썸네일 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.subject",
                        verbose_name="과목",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험",
                "verbose_name_plural": "시험 목록",
                "db_table": "exams",
            },
        ),
        migrations.CreateModel(
            name="ExamDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("duration_time", models.PositiveSmallIntegerField(verbose_name="제한 시간(분)")),
                ("access_code", models.CharField(max_length=64, verbose_name="접근 코드")),
                ("open_at", models.DateTimeField(verbose_name="오픈 일시")),
                ("close_at", models.DateTimeField(verbose_name="마감 일시")),
                ("questions_snapshot_json", models.JSONField(verbose_name="문항 스냅샷(JSON)")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVATED", "시험 응시 가능"), ("DEACTIVATED", "시험 비활성화")],
                        default="DEACTIVATED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_deployments",
                        to="courses.cohort",
                        verbose_name="기수",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="exams.exam",
                        verbose_name="시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 배포",
                "verbose_name_plural": "시험 배포 목록",
                "db_table": "exam_deployments",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255, verbose_name="문항")),
                ("prompt", models.TextField(blank=True, null=True, verbose_name="지문")),
                ("blank_count", models.PositiveSmallIntegerField(default=0, verbose_name="빈칸 수")),
                ("options_json", models.TextField(blank=True, null=True, verbose_name="보기(JSON)")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FILL_IN_BLANK", "빈칸 채우기"),
                            ("ORDERING", "순서 정렬"),
                            ("MULTI_SELECT", "다지선다"),
                            ("SHORT_ANSWER", "주관식 단답형"),
                            ("OX", "OX퀴즈"),
                        ],
                        max_length=20,
                        verbose_name="문항 유형",
                    ),
                ),
                ("answer", models.JSONField(verbose_name="정답(JSON)")),
                ("point", models.PositiveSmallIntegerField(verbose_name="배점")),
                ("explanation", models.TextField(verbose_name="해설")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 문항",
                "verbose_name_plural": "시험 문항 목록",
                "db_table": "exam_questions",
            },
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(verbose_name="응시 시작 일시")),
                ("cheating_count", models.PositiveSmallIntegerField(default=0, verbose_name="부정행위 횟수")),
                ("answers_json", models.JSONField(verbose_name="제출 답안(JSON)")),
                ("score", models.PositiveSmallIntegerField(default=0, verbose_name="점수")),
                ("correct_answer_count", models.PositiveSmallIntegerField(default=0, verbose_name="정답 수")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exams.examdeployment",
                        verbose_name="시험 배포",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="응시자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 제출",
                "verbose_name_plural": "시험 제출 목록",
                "db_table": "exam_submissions",
            },
        ),
    ]
