# Generated by Django 5.2.8 on 2026-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="thumbnail_img_url",
            field=models.CharField(default="default_img_url", max_length=255, verbose_name="썸네일 URL"),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="duration_time",
            field=models.PositiveSmallIntegerField(default=60, verbose_name="제한 시간(분)"),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="status",
            field=models.CharField(
                choices=[("ACTIVATED", "시험 응시 가능"), ("DEACTIVATED", "시험 비활성화")],
                default="DEACTIVATED",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="examdeployment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
