# Generated by Django 5.2.8 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_exam_thumbnail_img_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "단일선다"),
                    ("FILL_IN_BLANK", "빈칸 채우기"),
                    ("ORDERING", "순서 정렬"),
                    ("MULTI_SELECT", "다지선다"),
                    ("SHORT_ANSWER", "주관식 단답형"),
                    ("OX", "OX퀴즈"),
                ],
                max_length=20,
                verbose_name="문항 유형",
            ),
        ),
    ]
