# Generated by Django 5.2.8 on 2026-01-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, verbose_name="카테고리명")),
                ("status", models.BooleanField(default=True, verbose_name="활성 상태")),
            ],
            options={
                "verbose_name": "게시글 카테고리",
                "verbose_name_plural": "게시글 카테고리 목록",
                "db_table": "post_category",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                ("is_visible", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("is_notice", models.BooleanField(default=False, verbose_name="공지사항 여부")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="posts.postcategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
                "db_table": "post",
            },
        ),
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.CharField(max_length=255, verbose_name="파일 URL")),
                ("file_name", models.CharField(max_length=50, verbose_name="파일명")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 첨부파일",
                "verbose_name_plural": "게시글 첨부파일 목록",
                "db_table": "post_attachments",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=300, verbose_name="내용")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 댓글",
                "verbose_name_plural": "게시글 댓글 목록",
                "db_table": "post_comment",
            },
        ),
        migrations.CreateModel(
            name="PostCommentTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="posts.postcomment",
                        verbose_name="댓글",
                    ),
                ),
                (
                    "tagged_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="태그된 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 태그",
                "verbose_name_plural": "댓글 태그 목록",
                "db_table": "post_comment_tags",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.TextField(verbose_name="이미지 URL")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 이미지",
                "verbose_name_plural": "게시글 이미지 목록",
                "db_table": "post_images",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_liked", models.BooleanField(default=True, verbose_name="좋아요 여부")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 좋아요",
                "verbose_name_plural": "게시글 좋아요 목록",
                "db_table": "post_likes",
                "unique_together": {("user", "post")},
            },
        ),
    ]
