# Generated by Django 5.2.8 on 2026-01-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_notice",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_visible",
        ),
    ]
